import numpy as np
arr=np.array([[1,2,3],[2,3,4]])
print(arr)


In [10]:
import numpy as np
arr=np.array([5,6,7], dtype=complex)
print(arr)


[5.+0.j 6.+0.j 7.+0.j]


In [21]:
 import numpy as np
dt=np.dtype('i4')
print(dt)

int32


In [20]:
import numpy as np
a=np.array([[9,3,9],[1,3,8]])
b=np.array([[5,7,8],[8,2,4]])
g=a-b
print(g)
print()
print(np.subtract(a,b))
print()
print(np.multiply(a,b))
print()
print(np.exp(b))


[[ 4 -4  1]
 [-7  1  4]]

[[ 4 -4  1]
 [-7  1  4]]

[[45 21 72]
 [ 8  6 32]]

[[ 148.4131591  1096.63315843 2980.95798704]
 [2980.95798704    7.3890561    54.59815003]]


In [37]:
import numpy as np
a=np.array([[97,13,19],[12,37,8]])  
b=np.array([[5,7,8],[8,2,4]])
print(np.array_equal(a,b))
print(a.sum())
print(a.max())
print(a.mean())
print(b.mean())
print(np.std(b))


False
186
97
31.0
5.666666666666667
2.2110831935702664


In [41]:
import numpy as np
a=np.array([[97,13,19],[12,37,8]])
b=np.array([[5,7,8],[8,2,4]])
print(a.shape)
print(b.shape)
print()
a.shape=(3,2)
print(a)
print()
b.shape=(1,6)
print(b)
print()
c=np.arange(24)
d=c.reshape(2,4,3)
print(d)

(2, 3)
(2, 3)

[[97 13]
 [19 12]
 [37  8]]

[[5 7 8 8 2 4]]

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [42]:
import numpy as np
a=np.array([[97,13,19],[12,37,8]])
print(a.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False



In [21]:
x=[1,2,3,6,3]
a=np.asarray(x)
print(a)
y = [(1,2,3),(4,5)]
i = np.asarray(y)
print(i)
z=[0.0,0.4,0.5,0.2,0.9,20]
b=np.zeros(6);
print(b)

[1 2 3 6 3]
[(1, 2, 3) (4, 5)]
[0. 0. 0. 0. 0. 0.]


C:\Users\GPREC\AppData\Local\Temp\ipykernel_18232\2386379711.py:5: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  i = np.asarray(y)


In [22]:
a=np.array(range(6)).reshape(2,3)
print(a)
print(a.transpose())
b=np.array([2,7],float)
c=np.array([6,8,3,6],float)
d=np.array([25,0],float);
np.concatenate((b,c,d))

[[0 1 2]
 [3 4 5]]
[[0 3]
 [1 4]
 [2 5]]


array([ 2.,  7.,  6.,  8.,  3.,  6., 25.,  0.])